### ISSUE TITLE
drop_seqs by name

### ISSUE THREAD

**Issue by eugeniasampayo** [marine-ecologist/tidyseqs#3]
There are no changes to the plot, with or without the drop_seqs inclusion within the function. I have run this with either a vector droplist (droplist_seqs = c("A) first and then using drop_seqs=droplist_seqs in the function) or by directly listing the sequences in the function cf the example below. 

tidyseqs::extract_seqs(folder_path, meta, type="absolute", onlyprofile = TRUE) %>% 
  filter_seqs(., drop_samples = "II", threshold=1000, drop_seqs="A") %>%
  plot_seqs(type="plotly", cluster="bray") 

We'd like to remove all sequences belonging to clade A here, making sure that this is case sensitive to capitals and allowing partial matching.  The reason is that the 'clade' is listed in the output as a capital letter but sub-sequences have lower case letters and should be kept if there is for example C1a.

**Comment by marine-ecologist** [comment]
Edit 15/5/04: as of 0.9003 both now `drop_samples` and `drop_seqs` now work with partial matches (case sensitive)

For example:

```
extract_seqs(folder_path_TUR18, type="absolute", onlyprofile = TRUE) %>%
  filter_seqs(threshold=1000) |> 
  plot_seqs(type="plotly", folder=folder_path_TUR18, cluster="bray")
```

![Screenshot 2024-05-15 at 4 10 31 pm](https://github.com/marine-ecologist/tidyseqs/assets/93563980/2c731faa-bc2d-455b-b6a0-501433bcf665)


vs

```
extract_seqs(folder_path_TUR18, type="absolute", onlyprofile = TRUE) %>%
  filter_seqs(drop_seqs="C", threshold=1000) %>% 
  plot_seqs(type="plotly", folder=folder_path_TUR18, cluster="bray")
```

![Screenshot 2024-05-15 at 4 10 37 pm](https://github.com/marine-ecologist/tidyseqs/assets/93563980/f5c39366-dd77-43ec-88e4-c4e1b57e3bf8)
